"""
gen_holidays.py
Generates Oracle UPDATE statements for date_dim's Malaysian public
holidays using the `holidays` library, instead of hardcoding dates.


Usage:
    pip install holidays

    python gen_holidays.py                 -> 2019..2022 (default)
    python gen_holidays.py 2026            -> 2026 only
    python gen_holidays.py 2018 2026       -> 2018..2026 inclusive range
    python gen_holidays.py 2019 2023 2026  -> those 3 years exactly

    python gen_holidays.py 2018 2026 > holiday_update.sql

Then run the generated file against your schema:  @holiday_update.sql

The generated file RESETS only the years it covers, so regenerating a
partial range (say 2025 2026) leaves earlier years untouched. Use this
after extending the calendar with load_date_dim_incremental(<year>).
"""
import sys
import holidays


def parse_years(argv):
    """0 args -> default range. 1 arg -> that year. 2 args -> inclusive
    range. 3+ args -> exactly those years."""
    if not argv:
        return [2019, 2020, 2021, 2022]
    try:
        vals = [int(a) for a in argv]
    except ValueError:
        print(f"ERROR: years must be integers, got: {' '.join(argv)}",
              file=sys.stderr)
        sys.exit(1)
    for v in vals:
        if not 1900 <= v <= 2100:
            print(f"ERROR: year out of range: {v}", file=sys.stderr)
            sys.exit(1)
    if len(vals) == 1:
        return vals
    if len(vals) == 2:
        lo, hi = min(vals), max(vals)
        return list(range(lo, hi + 1))
    return sorted(set(vals))


YEARS = parse_years(sys.argv[1:])

# date_dim.holiday_name is VARCHAR2(80) - anything longer raises
# ORA-12899 and aborts the load. Keep this in sync with create_dwh.sql.
MAX_NAME_LEN = 80

# National-level Malaysian holidays (no state subdivision).
# Pass e.g. subdiv="KUL" for Kuala Lumpur-specific days if needed.
my_holidays = holidays.Malaysia(years=YEARS)

# Translate the library's Malay names to short English labels for
# cleaner analysis output. Anything unmapped keeps its original name.
# Order matters: label() uses startswith, so longer keys go first.
NAME_MAP = {
    "Tahun Baharu Cina (Hari Kedua)": "Chinese New Year",
    "Tahun Baharu Cina": "Chinese New Year",
    "Hari Pekerja": "Labour Day",
    "Hari Wesak": "Wesak Day",
    "Hari Raya Puasa (Hari Kedua)": "Hari Raya Aidilfitri",
    "Hari Raya Puasa": "Hari Raya Aidilfitri",
    "Hari Raya Qurban (Hari Kedua)": "Hari Raya Haji",
    "Hari Raya Qurban": "Hari Raya Haji",
    "Awal Muharam": "Awal Muharram",
    "Hari Kebangsaan": "Merdeka Day",
    "Hari Malaysia": "Malaysia Day",
    "Maulidur Rasul": "Prophet Muhammad Birthday",
    "Hari Deepavali": "Deepavali",
    "Hari Krismas": "Christmas Day",
    "Tahun Baharu": "New Year",
    # --- added: these came through unmapped ---
    # NOTE: these keys are the Malay names. Newer versions of the
    # `holidays` library return ENGLISH names for Malaysia, which do not
    # match these keys and so fall through to the raw name. That is fine
    # now that holiday_name is VARCHAR2(80) - the longest English name,
    # "Day of Installation of the 16th Yang di-Pertuan Agong", is 53.
    "Hari Keputeraan Rasmi Seri Paduka Baginda Yang di-Pertuan Agong":
        "Agong Birthday",
    "Hari Keputeraan Nabi Muhammad S.A.W.": "Prophet Muhammad Birthday",
    "Hari Pertabalan Yang di-Pertuan Agong": "Agong Coronation",
    "Peristiwa (pilihan raya umum)": "General Election",
    "Peristiwa": "Special Holiday",
}

def label(raw: str) -> str:
    # Strip "Cuti " (observed-day prefix) before mapping
    base = raw.replace("Cuti ", "").strip()
    for k, v in NAME_MAP.items():
        if base.startswith(k):
            return v
    return base.replace("'", "''")   # escape quotes for SQL

# Group dates by label so we emit one UPDATE per holiday name
grouped: dict[str, list] = {}
for d, raw in sorted(my_holidays.items()):
    grouped.setdefault(label(raw), []).append(d)

# Fail loudly rather than let the SQL die halfway through with ORA-12899
too_long = [n for n in grouped if len(n) > MAX_NAME_LEN]
if too_long:
    print("ERROR: these holiday names exceed date_dim.holiday_name "
          f"VARCHAR2({MAX_NAME_LEN}):", file=sys.stderr)
    for n in too_long:
        print(f"  ({len(n)}) {n}", file=sys.stderr)
    print("Add a NAME_MAP entry for each, then re-run.", file=sys.stderr)
    sys.exit(1)

YEAR_LO, YEAR_HI = min(YEARS), max(YEARS)
ARGS = " ".join(str(y) for y in YEARS)

print("-- Malaysian public holidays generated by gen_holidays.py")
print(f"-- Source: python `holidays` library, years {YEARS}")
print(f"-- {sum(len(v) for v in grouped.values())} holiday dates, "
      f"{len(grouped)} distinct holidays")
print("-- DO NOT EDIT BY HAND - regenerate with:")
print(f"--     python gen_holidays.py {ARGS} > holiday_update.sql\n")

# Reset first, so re-running this file after a correction clears any
# holidays that are no longer in the list instead of leaving them behind.
#
# SCOPED to the generated years ONLY. An unscoped reset would wipe the
# holidays of every other year and never put them back - so generating
# just 2025-2026 would silently destroy 2019-2022.
print("UPDATE date_dim SET holiday_ind = 'N', holiday_name = NULL")
print(" WHERE holiday_ind = 'Y'")
if YEAR_LO == YEAR_HI:
    print(f"   AND cal_year = {YEAR_LO};\n")
elif YEARS == list(range(YEAR_LO, YEAR_HI + 1)):
    print(f"   AND cal_year BETWEEN {YEAR_LO} AND {YEAR_HI};\n")
else:
    print(f"   AND cal_year IN ({', '.join(str(y) for y in YEARS)});\n")

for name, dates in grouped.items():
    date_list = ",\n                    ".join(
        f"DATE '{d.isoformat()}'" for d in dates)
    print(f"UPDATE date_dim SET holiday_ind = 'Y', "
          f"holiday_name = '{name}'")
    print(f" WHERE cal_date IN ({date_list});")
    print()

print("COMMIT;")
